name: aphotographie
favicon: null
layout_spectrum: 0
typography_spectrum: 0.91714
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#777777'
    - '#b9b9b9'
    - '#313131'
    - '#dcdcdc'
    - '#010101'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
