name: aphotographie
favicon: null
layout_spectrum: 0.26223
typography_spectrum: 0.96189
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#150D0E'
    - '#D8C6B4'
    - '#F3E3E6'
    - '#6E5C4B'
    - '#5A3717'
  brandStrength: 0.8021277
  lightness: 0.397399197332561
  saturation: 0.55892891343683
  rhythmicContrast: 0.1496985089033842
purpose: []
